/// Une ligne par compte et par mois avec au moins une opération.
table 'Activité mensuelle'
	lineageTag: fd23dcb7-057d-5fcd-8879-80f03d149979

	column 'Id compte'
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 8795aec4-a3f8-5a28-ac3a-fa5a585eb66b
		summarizeBy: none
		sourceColumn: Id compte

		annotation SummarizationSetBy = Automatic

	column Mois
		dataType: dateTime
		formatString: mmmm yyyy
		isHidden
		lineageTag: dc28047b-c248-5e42-b9c2-4f1b06d9d68a
		summarizeBy: none
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

	column 'Client actif'
		dataType: int64
		formatString: 0
		lineageTag: 340d7810-b71b-51d3-999d-2c42ad146814
		summarizeBy: none
		sourceColumn: Client actif

		annotation SummarizationSetBy = Automatic

	column 'Opérations client'
		dataType: int64
		formatString: #,##0
		lineageTag: b971c604-6f7a-5439-aacd-0fd777c1f36a
		summarizeBy: none
		sourceColumn: Opérations client

		annotation SummarizationSetBy = Automatic

	column 'Paiements carte'
		dataType: int64
		formatString: #,##0
		lineageTag: 5de86b96-e945-5123-a1d4-09d93a92fc49
		summarizeBy: none
		sourceColumn: Paiements carte

		annotation SummarizationSetBy = Automatic

	column 'Paiements refusés'
		dataType: int64
		formatString: #,##0
		lineageTag: c2eecd36-5783-5e62-9d05-742adf47bb62
		summarizeBy: none
		sourceColumn: Paiements refusés

		annotation SummarizationSetBy = Automatic

	column 'Dépenses carte'
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 2443da53-40c4-536c-b5b8-ac8f1e98e3a0
		summarizeBy: none
		sourceColumn: Dépenses carte

		annotation SummarizationSetBy = Automatic

	column 'Dépôts'
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 5dc7e509-01d1-5a68-8609-09ccf51d58d5
		summarizeBy: none
		sourceColumn: Dépôts

		annotation SummarizationSetBy = Automatic

	partition 'Activité mensuelle' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "fait_activite_mensuelle.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {{"Id compte", Int64.Type}, {"Mois", type date}, {"Client actif", Int64.Type}, {"Opérations client", Int64.Type}, {"Paiements carte", Int64.Type}, {"Paiements refusés", Int64.Type}, {"Dépenses carte", type number}, {"Dépôts", type number}}, "en-US")
				in
				    TypedColumns

	annotation PBI_ResultType = Table
