/// Canal d'acquisition du client.
table Canal
	lineageTag: e71512b9-840f-52b2-b5df-21d54f70292d

	column 'Code canal'
		dataType: string
		isHidden
		lineageTag: a53ec691-1665-54e0-a57c-41026e94d3c8
		summarizeBy: none
		sourceColumn: Code canal

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: b272c6df-c5d8-5dcf-b1fd-3382de15c897
		summarizeBy: none
		sourceColumn: Canal
		sortByColumn: 'Ordre canal'

		annotation SummarizationSetBy = Automatic

	column 'Ordre canal'
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 8a05683c-63f9-576d-9997-4ee91f9ba0c7
		summarizeBy: none
		sourceColumn: Ordre canal

		annotation SummarizationSetBy = Automatic

	partition Canal = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "dim_canal.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    TypedColumns = Table.TransformColumnTypes(PromotedHeaders, {{"Code canal", type text}, {"Canal", type text}, {"Ordre canal", Int64.Type}}, "en-US")
				in
				    TypedColumns

	annotation PBI_ResultType = Table
